# Generated by Django 5.1.1 on 2024-09-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Website', '0007_alter_produit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='produit/'),
        ),
    ]
