# Generated by Django 5.2.1 on 2025-07-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Website', '0009_produit_image3_produit_image4'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'verbose_name_plural': 'Produit et Service'},
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(),
        ),
    ]
